// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson73770c33DecodeGithubComKamaiuOandaGoModel(in *jlexer.Lexer, out *AccountConfigurationError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "clientConfigureRejectTransaction":
			if in.IsNull() {
				in.Skip()
				out.ClientConfigureRejectTransaction = nil
			} else {
				if out.ClientConfigureRejectTransaction == nil {
					out.ClientConfigureRejectTransaction = new(ClientConfigureRejectTransaction)
				}
				(*out.ClientConfigureRejectTransaction).UnmarshalEasyJSON(in)
			}
		case "lastTransactionID":
			out.LastTransactionID = TransactionID(in.String())
		case "errorCode":
			out.ErrorCode = string(in.String())
		case "errorMessage":
			out.ErrorMessage = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson73770c33EncodeGithubComKamaiuOandaGoModel(out *jwriter.Writer, in AccountConfigurationError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"clientConfigureRejectTransaction\":"
		out.RawString(prefix[1:])
		if in.ClientConfigureRejectTransaction == nil {
			out.RawString("null")
		} else {
			(*in.ClientConfigureRejectTransaction).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"lastTransactionID\":"
		out.RawString(prefix)
		out.String(string(in.LastTransactionID))
	}
	{
		const prefix string = ",\"errorCode\":"
		out.RawString(prefix)
		out.String(string(in.ErrorCode))
	}
	{
		const prefix string = ",\"errorMessage\":"
		out.RawString(prefix)
		out.String(string(in.ErrorMessage))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountConfigurationError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson73770c33EncodeGithubComKamaiuOandaGoModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountConfigurationError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson73770c33EncodeGithubComKamaiuOandaGoModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountConfigurationError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson73770c33DecodeGithubComKamaiuOandaGoModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountConfigurationError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson73770c33DecodeGithubComKamaiuOandaGoModel(l, v)
}
